AWSTemplateFormatVersion: 2010-09-09
Description: ---
Resources:
myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: 
    ImageId:  ami-09d3b3274b6c5d4aa
    InstanceType: 
    Monitoring: true|false
    

